### ISSUE TITLE
After successful installation, running polygnn shows error with torch

### ISSUE THREAD

**Issue by madhubantimukherjee** [Ramprasad-Group/polygnn#5] opened 2023-04-10 21:26 UTC
Running "poetry run python example.py --polygnn" shows the following error:

![1](https://user-images.githubusercontent.com/31185879/231001564-daa84985-069c-4b9a-b37f-832bfb951afd.png)

While installing, I got this message. 

![2](https://user-images.githubusercontent.com/31185879/231001624-56738b05-4df5-4bce-bb09-e11de64a2b7c.png)

Please look into this issue. Thanks!

**Comment by rishigurnani** [comment] 2023-04-10 21:58
@madhubantimukherjee can you please tell me which package versions you are using? This is what I see.
```
polygnn$ poetry run python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torch_geometric
>>> torch.__version__
'1.9.1+cu102'
>>> torch_geometric.__version__
'2.0.4'
```

**Comment by rishigurnani** [comment] 2023-04-11 23:00
OK, it looks like you have a more recent version of `torch_geometric` than I do. This is perfectly fine. I need to make this repo compatible with that version. I will get back to you when it is complete.

**Comment by rishigurnani** [comment] 2023-04-12 01:14
@madhubantimukherjee  I believe the issue is fixed in the last version of the code. Please pull this version and redo the installation steps 6-8 in the README. Let me know how it goes.

**Comment by madhubantimukherjee** [comment] 2023-04-12 16:26
@rishigurnani Thanks a lot. I will pull the new version and redo the installation and will let you know soon

**Comment by rishigurnani** [comment] 2023-04-12 17:34
Great! You should be able to get the new version by doing “poetry update polygnn”.

**Comment by madhubantimukherjee** [comment] 2023-04-14 14:56
Hi, @rishigurnani I reinstalled and did a test run. It just got completed successfully. I hope the issue is resolved now. Thanks a lot!

**Comment by rishigurnani** [comment] 2023-04-14 17:09
Awesome! Closing this issue then.

**Closed by rishigurnani** 2023-04-14 17:09 UTC
