### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by madhubantimukherjee** [Ramprasad-Group/polygnn#18] opened 2023-08-04 21:45 UTC
HI, while installing polyGNN with a virtual environment, we face the following issue:
![image](https://github.com/Ramprasad-Group/polygnn/assets/31185879/5fcc3a27-7767-4122-bf8a-4985f074e72f)

Could you please help us out?
Thanks in advance!

**Comment by rishigurnani** [comment] 2023-08-07 13:03
Hi @madhubantimukherjee I do not have that issue.

What is the output of `git log` in the root directory?

**Comment by madhubantimukherjee** [comment] 2023-08-14 20:22
Here it is. 
[git_log.txt](https://github.com/Ramprasad-Group/polygnn/files/12339325/git_log.txt)

**Comment by rishigurnani** [comment] 2023-08-14 23:49
Thank you. It looks like you have the latest version, so no problem there. It is strange because I am able to set up `polygnn` with no problem on T2. Any idea why this may be?

If not, I ask that you delete the `polygnn` directory and start over with the installation. Please send me each command and the outputs. The first command I'm interested in is `which poetry`. After that, you can start from Step 2 of the README.

**Comment by madhubantimukherjee** [comment] 2023-08-15 20:13
Thanks! Is it because we are using python3.9? not sure! I have attached all the commands and corresponding outputs. Please have a look

![image](https://github.com/Ramprasad-Group/polygnn/assets/31185879/16419120-df01-4a5b-b250-a0bf6876ff1a)
![image](https://github.com/Ramprasad-Group/polygnn/assets/31185879/0742ce84-3957-4fa7-b98d-43e1aeb6d001)
![image](https://github.com/Ramprasad-Group/polygnn/assets/31185879/abda04ee-1c0b-46cf-934d-378a2f1050a3)
![image](https://github.com/Ramprasad-Group/polygnn/assets/31185879/9e73e3b5-079b-4a95-a449-f581bcd1c7a4)
![image](https://github.com/Ramprasad-Group/polygnn/assets/31185879/daa0d0ec-b8e7-47d4-90f4-cf5035acc218)

**Comment by rishigurnani** [comment] 2023-08-15 22:03
Hi @madhubantimukherjee, that may be the cause! Can you try using Python3.7?

**Comment by madhubantimukherjee** [comment] 2023-08-17 21:53
Yeah that was the issue I guess. So with python 3.7 I successfully installed it. Thanks! However, does it only work with python 3.7? It seems so

**Comment by rishigurnani** [comment] 2023-08-18 11:59
Yes, it only works with 3.7.

I will close the issue since it has been resolved.

**Closed by rishigurnani** 2023-08-18 11:59 UTC
